export const quartos = [
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":1
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":2
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":3
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":4
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":5
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":6
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":7
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":8
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":9
    },
    {
        "tipo":"Solteiro",
        "Status":"Vago",
        "ID":10
    }
]